// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnz3-799FUQzRklg7xNSU4sy-R_Q5AfTo',
    appId: '1:497549181695:web:de985a757553e69fc602ca',
    messagingSenderId: '497549181695',
    projectId: 'kinder-manager',
    authDomain: 'kinder-manager.firebaseapp.com',
    storageBucket: 'kinder-manager.appspot.com',
    measurementId: 'G-04ZTFWPC9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu6Ssb_ji9a5EbjxwKP9P68Atteutz41k',
    appId: '1:497549181695:android:a7fa4c8fad687357c602ca',
    messagingSenderId: '497549181695',
    projectId: 'kinder-manager',
    storageBucket: 'kinder-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmwvZCT4uw2UwHxCiao387l2tYWCxrtEE',
    appId: '1:497549181695:ios:46a730e32c463a84c602ca',
    messagingSenderId: '497549181695',
    projectId: 'kinder-manager',
    storageBucket: 'kinder-manager.appspot.com',
    iosClientId: '497549181695-t6d1bcr4urqsqbqhkspnmi561f7m7hdm.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.mobiledevelopement.group11.kindermanager',
  );
}
